{% set name = "pyproximal" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproximal-{{ version }}.tar.gz
  sha256: a51f14bd0ecdb62713e899320c0a515f1d48f35122b216c54a9329cb4d189ae9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15.0, <2.0.0
    - scipy >=1.8.0
    - pylops >=2.0.0

test:
  imports:
    - pyproximal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PyLops/pyproximal
  summary: Python library implementing proximal operators to allow solving non-smooth, constrained convex problems with proximal algorithms.
  license: LGPL-3.0
  license_file: LICENSE.md
  dev_url: https://github.com/PyLops/pyproximal
  doc_url: https://pyproximal.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mrava87
    - mlondschien
