{% set name = "pyproximal" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyproximal-{{ version }}.tar.gz
  sha256: 2dc8f6fa268fefa2315a7245f352eb1562d487840117b562ddf30d37898a0274

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.12
    - pytest-runner
    - setuptools-scm
    - pip
  run:
    - python >=3.8.12
    - numpy >=1.15.0
    - scipy >=1.8.0
    - pylops >=2.0.0

test:
  imports:
    - pyproximal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyLops/pyproximal
  summary: Python library implementing proximal operators to allow solving non-smooth, constrained convex problems with proximal algorithms.
  license: LGPL-3.0
  license_file: LICENSE.md
  dev_url: https://github.com/PyLops/pyproximal
  doc_url: https://pyproximal.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mrava87
    - mlondschien
